import { NextRequest, NextResponse } from "next/server";
import { AnalysisResponseSchema } from "@/lib/schema";
import {
  createSharedReport,
  toggleReportVisibility,
} from "@/lib/share";
import { checkRateLimit } from "@/lib/rate-limit";
import { verifyAnalysis } from "@/lib/sign";

export const runtime = "nodejs";

const MAX_BODY_BYTES = 32_768;
const SHARE_ID_PATTERN = /^[\w-]{6,24}$/;

function getClientIp(request: NextRequest): string {
  if (request.ip) return request.ip;
  const realIp = request.headers.get("x-real-ip");
  if (realIp) return realIp;
  const forwardedFor = request.headers.get("x-forwarded-for");
  if (forwardedFor) {
    const ips = forwardedFor.split(",").map((ip) => ip.trim());
    return ips[ips.length - 1] || "unknown";
  }
  return "unknown";
}

function getSessionId(request: NextRequest): string | null {
  return request.cookies.get("candor_session")?.value ?? null;
}

// POST — Create a shared report
export async function POST(request: NextRequest) {
  try {
    const contentLength = request.headers.get("content-length");
    if (contentLength && parseInt(contentLength, 10) > MAX_BODY_BYTES) {
      return NextResponse.json({ error: "Request too large." }, { status: 413 });
    }

    const ip = getClientIp(request);
    const rateLimit = await checkRateLimit(ip);
    if (!rateLimit.allowed) {
      return NextResponse.json(
        { error: "Sharing limit reached. Try again in about an hour." },
        { status: 429 }
      );
    }

    const body = await request.json();
    const { analysis, source_url, article_title, token } = body as {
      analysis: unknown;
      source_url?: string;
      article_title?: string;
      token?: string;
    };

    // Validate the analysis payload
    const parsed = AnalysisResponseSchema.safeParse(analysis);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid report data." },
        { status: 400 }
      );
    }

    // Verify HMAC — only reports actually generated by our server can be shared
    if (!token || !verifyAnalysis(parsed.data, token)) {
      return NextResponse.json(
        { error: "Invalid report signature." },
        { status: 403 }
      );
    }

    const sessionId = getSessionId(request);

    const result = await createSharedReport(
      parsed.data,
      source_url ?? null,
      article_title ?? null,
      sessionId
    );

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
    const publicUrl = `${baseUrl}/report/${result.share_id}`;

    return NextResponse.json(
      { share_id: result.share_id, public_url: publicUrl },
      { status: 201 }
    );
  } catch {
    return NextResponse.json(
      { error: "Failed to create shared report." },
      { status: 500 }
    );
  }
}

// PATCH — Toggle visibility
export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const { share_id, is_public } = body as {
      share_id: string;
      is_public: boolean;
    };

    if (!share_id || typeof is_public !== "boolean" || !SHARE_ID_PATTERN.test(share_id)) {
      return NextResponse.json(
        { error: "Invalid request." },
        { status: 400 }
      );
    }

    const sessionId = getSessionId(request);
    if (!sessionId) {
      return NextResponse.json(
        { error: "Unauthorized." },
        { status: 403 }
      );
    }

    const result = await toggleReportVisibility(share_id, sessionId, is_public);

    if (!result.success) {
      return NextResponse.json(
        { error: "Report not found or not authorized." },
        { status: 403 }
      );
    }

    return NextResponse.json({ success: true, is_public });
  } catch {
    return NextResponse.json(
      { error: "Failed to update report." },
      { status: 500 }
    );
  }
}
