import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { AnalysisResponseSchema } from "@/lib/schema";
import {
  createSharedReport,
  toggleReportVisibility,
} from "@/lib/share";
import { checkRateLimit } from "@/lib/rate-limit";
import { verifyAnalysis } from "@/lib/sign";
import { getClientIp } from "@/lib/client-ip";
import { getSignedSessionId, setSignedSessionCookie } from "@/lib/session";
import { parseJsonBody } from "@/lib/safe-body";

export const runtime = "nodejs";

const MAX_BODY_BYTES = 32_768;
const SHARE_ID_PATTERN = /^[\w-]{6,24}$/;

/**
 * Verify CSRF token: the x-csrf-token header must match the candor_csrf cookie.
 * (Double-submit cookie pattern)
 */
function verifyCsrf(request: NextRequest): boolean {
  const csrfCookie = request.cookies.get("candor_csrf")?.value;
  const csrfHeader = request.headers.get("x-csrf-token");
  if (!csrfCookie || !csrfHeader) return false;
  return csrfCookie === csrfHeader;
}

// POST — Create a shared report
export async function POST(request: NextRequest) {
  try {
    // CSRF verification (double-submit cookie pattern)
    if (!verifyCsrf(request)) {
      return NextResponse.json(
        { error: "Invalid CSRF token." },
        { status: 403 }
      );
    }

    // Parse body with enforced byte limit
    let body: {
      analysis: unknown;
      source_url?: string;
      article_title?: string;
      token?: string;
    };
    try {
      body = await parseJsonBody(request, MAX_BODY_BYTES);
    } catch (err) {
      if (err instanceof Error && err.message === "BODY_TOO_LARGE") {
        return NextResponse.json({ error: "Request too large." }, { status: 413 });
      }
      return NextResponse.json({ error: "Invalid request." }, { status: 400 });
    }

    const ip = getClientIp(request);
    const rateLimit = await checkRateLimit(ip);
    if (!rateLimit.allowed) {
      return NextResponse.json(
        { error: "Sharing limit reached. Try again in about an hour." },
        { status: 429 }
      );
    }

    const { analysis, source_url, article_title, token } = body;

    // Validate the analysis payload
    const parsed = AnalysisResponseSchema.safeParse(analysis);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid report data." },
        { status: 400 }
      );
    }

    // Verify HMAC — only reports actually generated by our server can be shared
    if (!token || !verifyAnalysis(parsed.data, token)) {
      return NextResponse.json(
        { error: "Invalid report signature." },
        { status: 403 }
      );
    }

    // Get existing session ID or generate a new one
    const existingSessionId = getSignedSessionId(request);
    const sessionId = existingSessionId || randomUUID();

    const result = await createSharedReport(
      parsed.data,
      source_url ?? null,
      article_title ?? null,
      sessionId
    );

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
    const publicUrl = `${baseUrl}/report/${result.share_id}`;

    const response = NextResponse.json(
      { share_id: result.share_id, public_url: publicUrl },
      { status: 201 }
    );

    // Set signed session cookie if the user doesn't have one yet
    if (!existingSessionId) {
      setSignedSessionCookie(response, sessionId);
    }

    return response;
  } catch {
    return NextResponse.json(
      { error: "Failed to create shared report." },
      { status: 500 }
    );
  }
}

// PATCH — Toggle visibility (requires signed session + CSRF)
export async function PATCH(request: NextRequest) {
  try {
    // CSRF verification (double-submit cookie pattern)
    if (!verifyCsrf(request)) {
      return NextResponse.json(
        { error: "Invalid CSRF token." },
        { status: 403 }
      );
    }

    // Parse body with enforced byte limit
    let body: { share_id: string; is_public: boolean };
    try {
      body = await parseJsonBody(request, MAX_BODY_BYTES);
    } catch (err) {
      if (err instanceof Error && err.message === "BODY_TOO_LARGE") {
        return NextResponse.json({ error: "Request too large." }, { status: 413 });
      }
      return NextResponse.json({ error: "Invalid request." }, { status: 400 });
    }

    const { share_id, is_public } = body;

    if (!share_id || typeof is_public !== "boolean" || !SHARE_ID_PATTERN.test(share_id)) {
      return NextResponse.json(
        { error: "Invalid request." },
        { status: 400 }
      );
    }

    // Require signed session cookie for ownership verification
    const sessionId = getSignedSessionId(request);
    if (!sessionId) {
      return NextResponse.json(
        { error: "Unauthorized." },
        { status: 403 }
      );
    }

    const result = await toggleReportVisibility(share_id, sessionId, is_public);

    if (!result.success) {
      return NextResponse.json(
        { error: "Report not found or not authorized." },
        { status: 403 }
      );
    }

    return NextResponse.json({ success: true, is_public });
  } catch {
    return NextResponse.json(
      { error: "Failed to update report." },
      { status: 500 }
    );
  }
}
